Repository tl-its-umich-edu/student_explorer, pull requests merged in 2019-10, with the labels that each got.

#157 Updating About page based on revisions (#86)
  student_explorer/templates/student_explorer/about.html
Labels: user-facing

#156 Rearranging navigation bar (#151)
  student_explorer/templates/student_explorer/index.html
Labels: enhancement

#161 Improving application's handling of new advisors (#139)
  seumich/templates/seumich/student_list_partial.html
  seumich/urls.py
  seumich/views.py
Labels: enhancement

#168 Improving coverage of different AdvisorView cases and adding tests (#165)
  seumich/tests.py
  seumich/views.py
Labels: bug, enhancement

#164 Adding new template that appears for advisors with no students (#140)
  seumich/static/seumich/styles/main.scss
  seumich/templates/seumich/advisor_detail.html
  seumich/templates/seumich/advisor_without_students.html
  seumich/templates/seumich/student_list_partial.html
Labels: enhancement

#180 Updating README development notes and .env.sample (#150)
  .env.sample
  README.md
Labels: documentation

#182 Caching intermediate-level templates using student_list_partial (#181)
  seumich/templates/seumich/advisor_detail.html
  seumich/templates/seumich/class_site_detail.html
  seumich/templates/seumich/cohort_detail.html
  seumich/templates/seumich/student_list.html
  seumich/templates/seumich/student_list_partial.html
Labels: performance

#183 Add app overview and data source details #150
  README.md
Labels: documentation

#188 Making SAML entityId configurable (#187)
  student_explorer/settings.py
Labels: enhancement
