Repository tl-its-umich-edu/student_explorer, pull requests merged in 2020-04, with the labels that each got.

#236 Fix visualization and table text issues (#212)
  seumich/fixtures/dev_data_drop_create_and_insert.sql
  seumich/static/seumich/styles/_semixins.scss
  seumich/static/seumich/styles/main.scss
  seumich/templates/seumich/student_class_site_detail.html
Labels: bug, user-facing

#240 Create management application fixtures for local development (#239)
  .gitignore
  management/fixtures/cohorts.json
  management/fixtures/student_mentor_mappings.json
  management/import_fixtures.py
  management/scripts/import_master_data.py
  start-localhost.sh
  student_explorer/management/commands/import_manage_fixtures.py
Labels: enhancement

#241 Fix pagination on cohort management page.
  management/templates/management/cohort_list.html
  management/views.py
Labels: bug
